[git_status]
conflicted = "!="
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ğŸ“¦"
modified = "ğŸ“"

[directory]
truncation_symbol = "â€¦/"
style = "underline bold blue"
